### ISSUE TITLE
Error with join

### ISSUE THREAD

**Issue by erocs** [Civcraft/modmail_ticketmanager#10]
[2015-05-21T01:04:53] Waking... Processing modmail.
[2015-05-21T01:04:53] 2015-05-21 05:04:53.656787 - Error when attempting to review modmail on line number 219.  Exception:  <class 'requests.exception
s.HTTPError'>
Traceback (most recent call last):
  File "modmail_ticketmanager.py", line 890, in <module>
    mainloop()
  File "modmail_ticketmanager.py", line 873, in mainloop
    processModMail()
  File "modmail_ticketmanager.py", line 272, in processModMail
    log.debug('\n'.join(msg))
TypeError: sequence item 1: expected string, list found

**Comment by ttk2** [comment]
Looks like reddit was just down.

**Comment by erocs** [comment]
I fixed it on the server just haven't had a chance to check it in.

**Comment by rourke750** [comment]
@erocs Is this needed?

**Comment by erocs** [comment]
Checked in yesterday

**Comment by erocs** [comment]
Checked in yesterday
